### ISSUE TITLE
tile manifest tile name - longer names get munged into the same line

### ISSUE THREAD

**Issue by th3tick** [kelsin/18xx#105]
I have longer names some tiles that are really just ~3 numbers, but have an "idExtra" part of two characters.  It works sometimes fine, but when they get to 3 numbers, it tries putting them on the same line.
<img width="776" alt="Screen Shot 2019-11-11 at 8 57 43 AM" src="https://user-images.githubusercontent.com/48138042/68601501-abddcc80-0461-11ea-8313-888da80ae2bc.png">

**Comment by knauman** [comment]
It puts the Extra ID from the pervious tile on top of the next tile.

**Comment by th3tick** [comment]
That's partially true, but not always:

<img width="776" alt="Screen Shot 2019-11-11 at 12 52 44 PM" src="https://user-images.githubusercontent.com/48138042/68616396-333b3800-0482-11ea-94a5-d53e09e10375.png">

Note that K1 (a PR tile) has a previous PR in every direction from it, but no PR itself.  The floating PR is a bit telling, though.

**Comment by knauman** [comment]
Yep, that is what I see. Anything over the limit gets shoved down to where the next tile is or should be.
![snip1](https://user-images.githubusercontent.com/51214001/68616900-99788880-048b-11ea-958c-a467aa6e9104.jpg)
![snip2](https://user-images.githubusercontent.com/51214001/68616906-9e3d3c80-048b-11ea-9c63-44366808dd00.jpg)

**Comment by th3tick** [comment]
OK, I see what you're seeing and agree that's the effect.  

So what I've done is swap the widths in TileManifest.css for .TileManifest--Id and .TileManifest--Quantity, and then further lowered the width for .TileManifest--Quantity to 0.4.  This seems to resolve the problem for my needs.

**Comment by kelsin** [comment]
I don't personally have a use for the tile manifests right now. How are people using them. Are you all printing them out as a player-aid type of device? If so what other features would make them more usable? How should we lay them out, should we paginate? Should I try to duplicate DTG/AAG style manifests?

**Comment by th3tick** [comment]
I honestly don't have much use for the manifest either except as an easy way to validate the tiles w/o printing them all.  Thus the fix I have a pull request for is sufficient for all my needs - I have no intent to print them.

OTOH, a way to generate the small versions of the tiles as images to import into a tile upgrade doc would be hugely helpful.  I can't just click/copy or click/save on the images as-is, so I have to resort to ugly ways to get those images for illustrator to use.

**Comment by kelsin** [comment]
Image output is definitely a thing we want to have. I've also wanted to add a tile upgrade thing as well so if you specify upgrades we put them in the manifest. Will look into that when we look at this issue.

**Comment by th3tick** [comment]
This was fixed in 419ca92951184961a277d7ca3b7502a6496d6feb.
