### ISSUE TITLE
Slashed City Values 

### ISSUE THREAD

**Issue by knauman** [kelsin/18xx#106]
Some existing tiles have a slashed value that does not fit into the existing circle for values.
![slashed tile](https://user-images.githubusercontent.com/51214001/68602608-49d69480-046c-11ea-92ea-a2f9385042a4.jpg)

**Comment by kelsin** [comment]
Do we want to make value "circles" be able to be elongated to fit, or make the text smaller, or make the circle bigger in these cases?

**Comment by knauman** [comment]
I think an ellipse would work the best.
