### ISSUE TITLE
Ability to Rotate Company Names in Cities

### ISSUE THREAD

**Issue by knauman** [kelsin/18xx#107]
The names for Companies rotates with the city rotation. It is not possible to rotate the name a different rotation.
![company name rotated tile](https://user-images.githubusercontent.com/51214001/68603383-c5851100-046d-11ea-9e59-0c49de76dd59.jpg)

**Comment by kelsin** [comment]
Yeah, I need to make a pass and make sure that city text is like value text in that it's always "up".
