### ISSUE TITLE
Track/Tile Options

### ISSUE THREAD

**Issue by knauman** [kelsin/18xx#111]
A few track/tile options to add:
1: Colorized Track
2: Ferry Track (Usually Red Dashed)
3: Mountain Passes: a la 1841

**Comment by kelsin** [comment]
For 2, would using the current narrow gauge definition, but allowing the black color to be any color (like the number 1 suggestion) be ok? Or do we want a new style as well?

**Comment by knauman** [comment]
I believe it is shown as as red dashed with nothing between the dashes.

**Comment by kelsin** [comment]
1841 Pass support added by adding `pass:true` to any size 1 or 2 city element. Example added to atoms page.

**Comment by kelsin** [comment]
Examples of track color options on atom page.
