### ISSUE TITLE
Support for die-cutting layout for cards

### ISSUE THREAD

**Issue by shazzner** [kelsin/18xx#114]
As with the Tiles, adding additional support for more die cutting is pretty important. The card die used by DTG and xxpaper uses 1.5" width by 2.5" height on a snug 5x4 grid. See attached image.

![1837637_Sm_Rectangles_CST13774_Final](https://user-images.githubusercontent.com/691304/68776393-97cad400-05f5-11ea-906d-a030f3dc08f8.jpg)

I started looking at adding support to this myself but wanted to include an issue if there were any thoughts on this.

The main issue being that tiles jsx appears to be one large svg, where as the cards are padded out with css. Additionally the die is designed for a portrait layout where the cards are designed for landscape. So either design it such that the alignment pins are locked to the left margins or use something like `transform: rotate(90deg);` to rotate each card for a vertical layout.

@kelsin any thoughts?

**Comment by kelsin** [comment]
The way we've been doing this for other layouts is to not use `rotate` and just lay the cards out horizontally (In this case locking it to 4 across and 5 down). In this case it would mean putting the die pins on the side margin like you said. If anyone else gets to this before me I would prefer it be implemented in that style.

**Comment by shazzner** [comment]
I don't think I'll be able to work on this anytime soon, but I think it's a very useful feature to have!

**Comment by kelsin** [comment]
This is merged in, full options for how big cutlines, bleed and borders are. Also pre-set layouts for the DTG die and my custom mini-euro sized die.
