### ISSUE TITLE
support for small die-cut tiles

### ISSUE THREAD

**Issue by th3tick** [kelsin/18xx#116]
There is a standard for the small 1822-sized tiles for a die cutter.  It would be nice to have the tile generator able to generate that size and layout of tiles.  I've attached the die cutter overlay for that size.

[small hex overlay.pdf](https://github.com/kelsin/18xx/files/3847315/small.hex.overlay.pdf)

**Comment by kelsin** [comment]
Excellent, thanks for the link. I'm unfortunately in-between jobs with no laptop but hoping to have time to clear out the issues list during December!

**Comment by kelsin** [comment]
Just committed code for this, will close this in a sec once it's merged. It looks like that die uses 1.0625 as a size for flat to flat instead of exactly 1inches so I'm making sure to use that as well. I need someone to test this at some point for me :)
