### ISSUE TITLE
Sanuki Railway logo used for Stock Round in round tracker

### ISSUE THREAD

**Issue by michaeljb** [kelsin/18xx#118]
If anything other than "none" is selected for the Companies/Company Logos configuration, the Sanuki Railway logo is used in place of the text "SR" in the round tracker section of the Market. I discovered this while PnPing 1889 (where the Sanuki Railway company comes from) but in the webapp, this can be seen to affect all titles.

On the bright side, an easy enough workaround is to change config in between printing the different parts of the game.

**Comment by kelsin** [comment]
Right now company colors and logos are based solely on the text for any token. Need to separate raw tokens from company tokens and this will help fix weird issues like this.

**Comment by kelsin** [comment]
Should be fixed with the latest push that redoes a lot of how tokens operate and work. Please report any breakages or problems. Thanks!
