### ISSUE TITLE
Firefox: Company Logos "main" works with Map but not with Map - Paginated

### ISSUE THREAD

**Issue by michaeljb** [kelsin/18xx#119]
For example, with the "Rails on Boards" option selected for companies theme, the Sanuki Railway (in 1889) gets a blue color. It gets a blue charter and share cards, and a blue home (Marugame, I2) on the map.

However, when going to the _paginated_ map, the reserved home spot is a bright green, which is the color Sanuki gets when "match" is selected for the Company Logos setting instead of "main".

**Comment by michaeljb** [comment]
Looks like this didn't happen when I generated PDFs via the command line.

**Comment by michaeljb** [comment]
After further testing, this seems to happen in Firefox, but I'm getting the correct behavior with Chrome.

**Comment by kelsin** [comment]
Oh interesting, I'm overriding SVG colors with colors via CSS and might have hit some weird corner case with this. Thanks for finding it!
