### ISSUE TITLE
missing token colors and letters on 18EU companies

### ISSUE THREAD

**Issue by akvik** [kelsin/18xx#12]
The tokens for the 18EU companies:
Belgian National Railways,
Austrial Imperial Royal State, and
German State Railways

are blank on their charters and on the token page. I am pretty sure it has to do with the color specification - when I change the colors to "red" instead of "goldenrod" on BNR for instance, the tokens show up.

**Comment by kelsin** [comment]
Nice point, I hadn't gone through and edited this submitted game for the new colors, will do soon!

**Comment by kelsin** [comment]
These should be fixed, We've defined the standard colors (using all of the ones that Rails on Board sells) and made should those are always available. Also made sure 18EU was using those names.
