### ISSUE TITLE
support needed for 1825's tile 200

### ISSUE THREAD

**Issue by th3tick** [kelsin/18xx#126]
1825's tile 200 is referred to as a "pass-thru" tile.  It has a square behind the city.  It also has a square around the revenue, but I'm not sure how important that is to support, or whether the difference has any real meaning.

This request is for a way to add a square behind the circle.  It will probably only ever be used for this one tile, but with it, 1825 can be put into the tool, and is otherwise extremely hard to obtain any info on.
<img width="109" alt="Screen Shot 2019-12-04 at 12 12 42 AM" src="https://user-images.githubusercontent.com/48138042/70120908-cfdc9a00-162a-11ea-9f2b-f4e7b8d884d6.png">

**Comment by knauman** [comment]
This can already be accomplished using the Goods atom. To make it go behind the city, you’ll need to edit the hex.jsx file and move the “goods” above “cities”.

If you look at my fork, 1825 everything is there and done.

**Comment by knauman** [comment]
I’m not seeing the printing problem, but my local distributions are heavily modified.
![stripped output](https://user-images.githubusercontent.com/51214001/70147053-1d77f780-1669-11ea-9331-a3fd74c96619.jpg)

**Comment by kelsin** [comment]
@knauman when can we get that forked merged in?

**Comment by knauman** [comment]
My code for this (left is my file, right is yours):
app.jsx
![app_jsx](https://user-images.githubusercontent.com/51214001/71626839-d07a3900-2bb4-11ea-8f44-c5b1f835e91e.jpg)

hex.jsx
![hex_jsx](https://user-images.githubusercontent.com/51214001/71626685-239fbc00-2bb4-11ea-8c67-2e18b7635bf5.jpg)

util.js
![util_js](https://user-images.githubusercontent.com/51214001/71626707-30241480-2bb4-11ea-910f-add322d20cb0.jpg)

**Comment by kelsin** [comment]
@knauman brought in all of that except adding borders to outside of the hex. What was that needed for? Bleed on border tiles?

**Comment by knauman** [comment]
I’m pretty sure it was for bleed

**Comment by kelsin** [comment]
@th3tick can you check if the current code works for your 1825? The goods positioning and the borders should be better? At least I pulled in the other code, let me know if that's good.

@knauman that makes sense, I need to make sure bordered tiles output in their own group based on border color and NOT tile color for the tile output, I'll work on that later (maybe tomorrow?) and I'll make sure bleed does it to.

@knauman do you have any need for borders that aren't the all sides at once? I think now that map borders can be defined in a different way we can make tile borders always be all sides, but want to make sure with people using it.

**Comment by knauman** [comment]
I can’t think of any current tiles like this, but I’d want to leave in the option to not be forced to have all side be borders for tiles. More flexibility the better.

**Comment by kelsin** [comment]
Of course, will leave current options available and add in a simple form for the all sides case.

**Comment by knauman** [comment]
I did have need to make new borders layouts. I can send you these if you’d like them. I didn’t make my code backwards compatible (I don’t think it would be hard to add that), just went in and changed the maps that needed it. I believe I added 4-5 types and another called dotted.
![borders](https://user-images.githubusercontent.com/51214001/71629741-bd6f6500-2bc4-11ea-8ba9-1730400d2a45.jpg)

**Comment by th3tick** [comment]
The base tiles look good.  What's the trick to get the 1" die cut tile pattern?

**Comment by th3tick** [comment]
Nevermind on the question.  I've been using @knauman 's definition for tile 200, but I don't see anything on github yet.  Which file do the multi-color ones go in?

**Comment by th3tick** [comment]
So, the striped tiles are back to wide stripes, even in Acrobat.

**Comment by th3tick** [comment]
<img width="668" alt="Screen Shot 2019-12-31 at 11 28 20 AM" src="https://user-images.githubusercontent.com/48138042/71630527-af1f4a00-2bc0-11ea-9ada-66f3f87b2800.png">

**Comment by knauman** [comment]
That is strange, I don’t see that. Maybe it’s that Mac acting up again.

**Comment by th3tick** [comment]
It was, but this is not from your branch, either.  That's why I specifically used Acrobat to check.

**Comment by knauman** [comment]
With the black box on top of the city on tile 200. That must still be running the code before what I gave him. Don’t think he has instituted that into the code for all yet.

**Comment by th3tick** [comment]
So does that imply the gradient changes also aren't merged in yet?

**Comment by kelsin** [comment]
The gradient changes should be, looks like I fucked up the goods change.
I'll fix early tomorrow.

Chris

**Comment by kelsin** [comment]
Both changes should be in now. My files look like the ones posted above.

**Comment by th3tick** [comment]
All looks good now.  Closing.
