### ISSUE TITLE
Coordinates overlaid on the map

### ISSUE THREAD

**Issue by knauman** [kelsin/18xx#135]
Like the title, to make clearer, more colorful maps need the coordinates above since some maps utilize hex row 0.
![coord_placement](https://user-images.githubusercontent.com/51214001/71739625-96609f80-2e1f-11ea-8005-8f7354bccd1a.jpg)

**Comment by kelsin** [comment]
Should be all set now. Just changing the rendering order in Map.jsx should solve this.
