### ISSUE TITLE
Draw rivers on the map

### ISSUE THREAD

**Issue by knauman** [kelsin/18xx#137]
Allow the placement of lines depicting rivers or other natural boundaries not tied to tile edges to be drawn on the map.

I’d prefer it use the x-y coordinates of the map for layout.
![river](https://user-images.githubusercontent.com/51214001/71746453-9027ee80-2e32-11ea-81de-1d047789e6cb.jpg)

**Comment by kelsin** [comment]
When you say x-y, how do you mean, can you give me an example? Would probably want to use the same system for the borders.

**Comment by knauman** [comment]
Same coordinates that the map title uses so it isn’t tied to the tiles.

**Comment by kelsin** [comment]
Did this with the border system. Complicate coordinate system where you can reference spots on hexes simular to how you like hexes out, but it just draws lines on the map from point to point.

https://18xx.kelsin.net/docs/borders
