### ISSUE TITLE
spaces in game titles break "yarn print"

### ISSUE THREAD

**Issue by th3tick** [kelsin/18xx#142]
I'm not sure why it's looking for the title here rather than the filename (1825-U1.json).  Or maybe it's not liking dashes in the file/game name?

(node:69726) UnhandledPromiseRejectionWarning: Error: Cannot find module '../src/data/games/1825 Unit 1'
Require stack:
- /Users/rifleman/Dropbox/Board Games/18xx/18xx/bin/print.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /Users/rifleman/Dropbox/Board Games/18xx/18xx/bin/print.js:59:19
(node:69726) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:69726) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by th3tick** [comment]
That was from "yarn build && yarn print all".  Running it separately works fine:

% yarn print 1825-U1   ~/Dropbox/Board Games/18xx/18xx
yarn run v1.19.1
$ node ./bin/print.js 1825-U1
Printing 1825-U1/background
Printing 1825-U1/cards
Printing 1825-U1/charters
Printing 1825-U1/map
Printing 1825-U1/map-paginated
Printing 1825-U1/market
Printing 1825-U1/market-paginated
Printing 1825-U1/revenue
Printing 1825-U1/tile-manifest
Printing 1825-U1/tiles
Printing 1825-U1/tokens
✨  Done in 15.37s.

**Comment by kelsin** [comment]
Same as #143
