### ISSUE TITLE
yarn print confused by tiles-only game definition

### ISSUE THREAD

**Issue by th3tick** [kelsin/18xx#143]
I split 1825 into 14 different pieces so as to put the tiles into their source expansions by creating game jsons of only the "info" and "tiles" sections.  The goal was to print them separately with the matching background.pdf for easy sorting by expansion.

This appears to work fine for the web interface, but when I "yarn print" them (individually, b/c of the other bug I filed), I only get PDFs of the intro page you get when you go to the base page of the server, with the list of games, links to docs, etc.  This is what I get for backgrounds.pdf, cards.pdf, charters.pdf, map-paginated.pdf, map.pdf, etc. - 11 copies of the same file.

I'm not sure if this is related to spaces in the names, hyphens in the filenames, or only having info and tiles sections.

**Comment by kelsin** [comment]
Improved print to only print things that exist in the game being printed.

However this was caused by spaces in the hash in games/index.js, adding a comment to help that in the future.
