### ISSUE TITLE
add ability to alias tile names

### ISSUE THREAD

**Issue by th3tick** [kelsin/18xx#145]
Some games have their own idea of what a given tile should be called.  It would be nice to be able to add a list of aliases for tiles so that they don't need another definition to get the tile number right so it matches the rules or any other game references.

**Comment by kelsin** [comment]
This is done. Multiple features added:

- Custom tiles in a game file
- A game file can say that it's tile 2 is really tile 56, and the game draws them as 2 without redefining
- A tile can have an array of alias names that get compiled at load time
