### ISSUE TITLE
Right and left arrows (market)

### ISSUE THREAD

**Issue by Galatolol** [kelsin/18xx#28]
I'd love to see right and left arrows on market. And the possibility to have more than one.

![arrows](https://user-images.githubusercontent.com/10097748/57016039-3ecabe00-6c18-11e9-8e96-f85379408ae1.png)

**Comment by kelsin** [comment]
Arrows can now be `up`, `down`, `left`, or `right`. Any other string results in the ↻ symbol.

`left` and `down` appear in the bottom left of the cell. `up` appears in bottom right. `right` appears in the upper right. Would customizing this be useful?

The value can also be an arrow and will render each one (so using `left` and `down` together doesn't look good. Example:

```json
{ "value": 60, "label": 60, "legend": 0, "arrow": ["right", "down"] }
```

All of this is in current master.

**Comment by Galatolol** [comment]
Thanks!

>Would customizing this be useful?

I doubt it.

**Comment by kelsin** [comment]
Ok then for now it's good. Once new desires come about open another issue!
