### ISSUE TITLE
Emergency buying

### ISSUE THREAD

**Issue by kelsin** [kelsin/18xx#32]
* Aren't allow to sell treasury shares (Do you have to?)
* Double check sell by 3 limit

**Comment by LucasLBoyd** [comment]
When emergency buying, the company first uses all the liquid cash it has. If its still short, it must sell all treasury shares it has into the bank (stock moves down a space). Can sell more than 30% this way. If the company still does not have enough money, then the responsibility passes to the president.

**Comment by kelsin** [comment]
Perfect, ty @LucasLBoyd, have enough info to implement this now.
