### ISSUE TITLE
Allow card size to be specified and cutlines removed on demand.

### ISSUE THREAD

**Issue by kelsin** [kelsin/18xx#35]

**Comment by Galatolol** [comment]
@kelsin Could you tell me how can I reduce the distance between cards?

![distance](https://user-images.githubusercontent.com/10097748/58915768-0db34100-8722-11e9-87ea-8bd4b0128380.png)

(it will be sort of a workaround of this issue for me)

**Comment by kelsin** [comment]
This is without testing of course, but right now all of the cutlines are in CSS so it's probably:
left: https://github.com/kelsin/18xx/blob/master/src/index.css#L856
right: https://github.com/kelsin/18xx/blob/master/src/index.css#L869
top: https://github.com/kelsin/18xx/blob/master/src/index.css#L883
bottom: https://github.com/kelsin/18xx/blob/master/src/index.css#L896

... I don't know if it will work easily. Try it out, I'll try to get this to be customized asap.

**Comment by kelsin** [comment]
Allows options for removing cutlines and adding borders as well.

**Comment by kelsin** [comment]
This is merged in, full options for how big cutlines, bleed and borders are. Also pre-set layouts for the DTG die and my custom mini-euro sized die.
