### ISSUE TITLE
Handle minors via same companies field as majors

### ISSUE THREAD

**Issue by kelsin** [kelsin/18xx#39]

**Comment by wcraigtrader** [comment]
In 1867, there are 5 private companies, 10 yellow minor companies, 6 green minor companies, 8 major (aka stock aka public) companies, and the Canadian National railroad. The minor companies have different phase limits than the major companies, different maximums for loans, and the CN has its own rules. It would be nice to be able to capture all of those nuances while defining companies.

**Comment by kelsin** [comment]
Can be done at the same time as #69

**Comment by kelsin** [comment]
This might include changing how we define minors which does break some games. While I like the change to not include `minorPhases` I don't like how it duplicates a lot of stuff. Might want to make a generic type of company definition... but unsure right now.

**Comment by kelsin** [comment]
You can mark phases as `"minor": true` as well as companies. Companies will only display phases that have the same value as `minor` as they do (defaults to false). Does mean that for some games you duplicate phases that should be identical between the two, but better than nothing for now.
