### ISSUE TITLE
Map rendering problem

### ISSUE THREAD

**Issue by Galatolol** [kelsin/18xx#46]
When I render a game, for example:

`yarn build app`

`yarn print 1800`

The result is:
[map.pdf](https://github.com/kelsin/18xx/files/3217932/map.pdf)

**Comment by kelsin** [comment]
I think you meant to post map-paginated.pdf

I broke it with a stupid typo. What's even worse? My tests found the issue but I'm not in the habit of running them...

**Comment by ngeunit1** [comment]
I am still seeing the same issue here with the generated pdfs

**Comment by kelsin** [comment]
@ngeunit1 can you confirm what sha hash you're currently on, and what node version and OS you're using?

**Comment by ngeunit1** [comment]
SHA: 25c592747cbba65cdfd30a1fbf3f08e669bd928c
OS: Ubuntu
node: v10.16.0

I was also able to reproduce the same issue on win10 with node v12

**Comment by ngeunit1** [comment]
Also verified same result for Node v10.15.3.

**Comment by kelsin** [comment]
What problems are you seeing? The slight overlap on the tiles and borders? Is there something else?

**Comment by ngeunit1** [comment]
Yes, mostly just the overlap. I am seeing something similar on the tiles as well. Not sure if that is related but it covers the tile number for example.

![map_overlap](https://user-images.githubusercontent.com/633368/60639130-3d239f00-9def-11e9-8a77-c06c0d8c655b.PNG)

![tileoverlap](https://user-images.githubusercontent.com/633368/60639265-e2d70e00-9def-11e9-8753-526db9bf983e.PNG)

**Comment by kelsin** [comment]
That's really odd. I fixed the large overlap bug right after it appeared and it was a while ago. Shouldn't be happening on a recent build. (I can't duplicate that screenshot on windows, in docker, or on my mac).

Are you running `yarn build` prior to printing and does it succeed?

**Comment by ngeunit1** [comment]
Yes, I have been doing yarn build && yarn print all. And I am getting a compiled successfully result with no warnings/errors.

**Comment by kelsin** [comment]
Are you editing `config.json` at all? If so can you pastie what you're using in case there's a bug with something there?

**Comment by ngeunit1** [comment]
I reverted the changes I had on Ubuntu and the Win10 was a fresh pull from about an hour ago.

**Comment by kelsin** [comment]
What programs are you using to view the resulting pdfs? Can you send me (kelsin@valefor.com) or link a PDF that you generated that has the issue?

**Comment by ngeunit1** [comment]
(sorry for the waste of time) But the viewer seems to be the issue. On windows IE displays them improperly but Adobe Reader and SumatraPDF display them correctly. On Ubuntu, the default document viewer is incorrect and I just downloaded Okular and it looks fine.

**Comment by kelsin** [comment]
Interesting, will look into that just in case, it would be worthwhile to make sure that it's a spec thing that those readers don't respond to. Thanks!

**Comment by Galatolol** [comment]
In my case it was also the fault of the default PDF reader. I'll write which one once I get back to home.

**Comment by sareneFactorial** [comment]
The "large overlap" issue persists with PDFs generated using the latest AppImage release of the standalone app ([v1.0.0-beta.41](https://github.com/18xx-maker/18xx-maker/releases/tag/v1.0.0-beta.41)) on Arch Linux.

It renders correctly on Firefox 104.0.2 and Okular on Arch Linux.

It renders incorrectly, with the large overlaps and broken lines, with GIMP, LibreOffice Draw, and InkScape using Poppler/Cairo on Arch Linux, and Adobe Illustrator on Windows 11.
