### ISSUE TITLE
Not offered option to move Hunslet Steam Engine to child when splitting

### ISSUE THREAD

**Issue by joshyboy20k** [kelsin/18xx#55]
Per Section 6.7.4 bullet 11 "The splitting player may now reallocate cash, trains, and the Hunslet Steam Engine private company (if owned) between the parent and child in any manner they prefer." 

When splitting Georgetown in this game https://18xx.games/game/77266?action=272 I was not presented the option to move the Hunslet over to the child company.

**Comment by kelsin** [comment]
Need to add a new step in the split round to handle this and skip when the splitting corporation doesn't own the hunslet. Should be easy to add in tonight and break the games where people split a hunslet company.
