### ISSUE TITLE
Individual tiles rendering

### ISSUE THREAD

**Issue by Galatolol** [kelsin/18xx#56]
In browser it works fine, but when I set the `layout` option to `individual` in config.json and run `yarn print 1800`, the result tiles seem "oversized" as though they were made for die cutting.

Did I forget to do something?

[tiles.pdf](https://github.com/kelsin/18xx/files/3229700/tiles.pdf)

**Comment by kelsin** [comment]
Looks like it's displaying tile bleed on individual when it shouldn't be. Will take a look and hopefully fix tonight! Sorry about that.

**Comment by kelsin** [comment]
Are you on the latest code @Galatolol ? I can't duplicate. If I misspell 1individual1 I get nothing printed for tiles and with the proper name I get tiles without bleed.

**Comment by kelsin** [comment]
Did you remember to run `yarn build` with the latest code before you ran print? If not it will be printing with the code that was in place the last time you ran `yarn build`.

**Comment by Galatolol** [comment]
Seems to be working now. Indeed I must have incorrectly rebuilt the app.
