### ISSUE TITLE
Tiles for 18SY, 18SS, 1891 and 18NK

### ISSUE THREAD

**Issue by kelsin** [kelsin/18xx#57]

**Comment by knauman** [comment]
18NK needs 3 gray X04 tiles.

**Comment by kelsin** [comment]
Didn’t even see those in my set lol will find and get them in tonight!

**Comment by knauman** [comment]
Looking through the rest of the Japanese games now.

**Comment by knauman** [comment]
18SS is missing 4 gray tiles.
18SY is missing 2 gray cities,

**Comment by kelsin** [comment]
Wow I clearly didn’t pull out any of the gray sheets! Sorry!

**Comment by knauman** [comment]
They are with the shares and tokens. If you were going through quickly you’d miss them.

**Comment by kelsin** [comment]
Green 58 shouldn't exist, it should be 16, that's why the yellow 58's were set to 2! I entered the yellow and then overrode it with the green later. The tiles in my files will be labeled correct, so 5 yellow 58's and 2 green 16's. Thanks for finding all of the other errors, they are all fixed and green tiles are in. Some minor layout things should probably be fixed, but I think everything is accurate now!

**Comment by knauman** [comment]
Found 1 more error - Brown Tile 623 should have a value of 50.

**Comment by kelsin** [comment]
Should fixed now. Thanks!
