### ISSUE TITLE
Support for coloured outer border on tile values

### ISSUE THREAD

**Issue by LupoLoopy** [kelsin/18xx#58]
Would like support for coloured outer border on tile values/revenues.

User case - 1834  -Antwerp tile (F5) has a '30' value which pays on the map printed tile during green phase, meaning it's higher yield than a normal city during the same window.

Would be nice to be able to mark this up. I think an outer ring in the 'theme' colour for the green tiles around the black circle should do it.

**Comment by Galatolol** [comment]
I added this functionality, but it got me thinking that actually it should just be offboardRevenue (like Toronto in 1817), shouldn't it?

I've opened a pull request, so you can check it out: #62
