### ISSUE TITLE
Make share and token definitions easier for companies

### ISSUE THREAD

**Issue by kelsin** [kelsin/18xx#66]

**Comment by wcraigtrader** [comment]
In 1846, the major companies have variable numbers of tokens:

* 3-5 station tokens (first is free, one _may_ have a special price, the rest are full price)
* 2 stock/earnings tokens
* 3 extra tokens (for buying in privates that give tokens)

When I set `extraTokens` to `2` and `extraHomeTokens` to `1`, I'll get 2 stock tokens, and 6-8 icon tokens, which works (though 8-10 icon tokens and no stock tokens would be better).

In 1867, the minor companies each have 3 tokens (station / stock price / earnings). The major companies each have 5 tokens (3 station / stock price / earnings). The Canadian National railroad has 8 station tokens (no stock price or earnings). When I define 3 tokens for each major (and 8 for the CN), the charters look OK, but the number of tokens are bizarre:

| extraTokens | extraHomeTokens | icon tokens | stock tokens |
|:--:|:--:|:--:|:--:|
| unset | unset | 6 | 3 |
| 0 | 0 | 6 | 3 |
| 0 | 1 | 7 | 3 |
| 1 | 0 | 4 | 1 |
| 2 | 0 | 5 | 2 |
| 3 | 0 | 6 | 3 |

**Comment by kelsin** [comment]
Extra tokens defaults to 3 if under or set to 0 (the zero thing is a bug
which I’ll fix!)

In all of your examples the “stock” tokens are meant to be on the reverse
side of the icon tokens. So in the example where extra tokens is set to 1,
you have three map tokens (for stations single sided) and then one token
meant for par/market/race track which is double sided.

I’ll try to make this clearer both in field names and docs.

**Comment by wcraigtrader** [comment]
So, if I have this correct, in 1846, each major company should have 8-10 obverse tokens, plus 2 more reverse tokens. The correct settings for this are:

> "extraTokens": 2,
> "extraHomeTokens": 3,

In 1867, there should be 3 obverse tokens + 2 reverse tokens for each minor company, and 5 obverse tokens + 2 reverse tokens. That can be achieved with these settings:
> "extraTokens": 2,
> "extraHomeTokens": 0,

I might suggest renaming the variables `stockTokens` instead of `extraTokens` and `extraStationTokens` instead of `extraHomeTokens`.

**Comment by kelsin** [comment]
That sounds correct but you are 100% right about renaming. Part of cleaning up of tokens that I'll be doing soon (besides fixing bugs) will be to remove these fields and rename them. Also make the inverse double sided thing an option, and an option for how double sided should work, blah blah blah. Tons of options and better named fields.

**Comment by wcraigtrader** [comment]
Along these lines, I tried using the Atom examples (http://localhost:3000/tiles/atoms) to define better color combinations for the minor companies in 1867, to no avail. In particular, what I want is for the 10 yellow minors to have a yellow center bar with an accent color, and for the 6 green minors to have a green center bar with an accent color.  What I tried first was this:
```
    {
      "name": "Buffalo, Brantford, and Goderich",
      "minor": true,
      "abbrev": "BBG",
      "tokens": [ "" ],
      "color": "yellow/red"
    },
```
That changed the effective color for that company to black. Then I tried defining a custom token for the company, as follows:
```
    {
      "name": "Buffalo, Brantford, and Goderich",
      "minor": true,
      "abbrev": "BBG",
      "tokens": [
        {
          "label": "BBG",
          "token": {
            "type": "bar",
            "colors": [
              "yellow",
              "red"
            ]
          }
        }
      ],
      "color": "yellow"
    },
```
That crashed the token tab, hard.

**Comment by kelsin** [comment]
Yeah, in your first example that's the main color for the charters / card / etc, so that color needs to remain a standard color (like "Yellow").

To make the token you want it should be:
```
{
    "name": "Buffalo, Brantford, and Goderich",
    "minor": true,
    "abbrev": "BBG",
    "tokens": [...],
    "token": { "type": "bar", "colors": ["yellow", "red"] }
}```

**Comment by kelsin** [comment]
And it's true that there is NO reason you would know that from the current docs....

**Comment by kelsin** [comment]
The part of this that makes share and token definitions easier is done. I have not renamed or changed the behavior of the `extra...` fields that are still confusing. Keeping this open for that.
