### ISSUE TITLE
Support charters with a colour of white

### ISSUE THREAD

**Issue by iamds** [kelsin/18xx#71]
If you specify a company charter to be white, I think it would be nicer if the "abbrev" had a black circle round it, and the title bar had a thin black line to distinguish it from the body of the charter.

![image](https://user-images.githubusercontent.com/1041455/60641505-e97f7880-9e23-11e9-9053-eb322dfa40ea.png)

**Comment by kelsin** [comment]
Good ideas, will look at how I want to do this in a way that doesn't involve lots of hacks for white colors etc.

**Comment by wcraigtrader** [comment]
Maybe foreground and background colors? In 1867, it would be nice for the Canadian National Railway (CN) to have red letters on a white background for the name and abbreviation.

**Comment by kelsin** [comment]
Should support white for tokens too.
