### ISSUE TITLE
Errors and inconsistencies in 1834

### ISSUE THREAD

**Issue by ckarlof** [kelsin/18xx#73]
- Starting capital for 5p is $430, not $440
- 2 trains don't render info text on rust schedule
- Background color of permanent trains is yellow in 1830 and here it is gray
- Cost of 2Ts is $700, not $750
 
PR incoming to resolve these.

**Comment by kelsin** [comment]
Excellent, it's hard for me to double check anything that I don't own yet! Of course I make mistakes too so all of these corrections are incredibly great. Thanks!

**Comment by ckarlof** [comment]
No problem!
