### ISSUE TITLE
Distance between pins and tiles (die cutting)

### ISSUE THREAD

**Issue by Galatolol** [kelsin/18xx#85]
If I [understand correctly](http://localhost:3000/images/CST25449_Hexes_Clear_Crop.jpg), 37.5 is the distance to the border of an actual tile and not to those extra strips of colour.

Replacing    
`c.extraY = 25 + 37.5; // Half inch above the pins, rest below`
with 
`c.extraY = 25 + 27.5; // Half inch above the pins, rest below` 
(in src/tilesheet/utils.js)
seems to fix it, but I feel that this is not the optimal solution.

**Comment by Paperemail** [comment]
If you look at the code for the bleed on the die cut tool, he already had it set for die cut.

If you noticed it moved it down for the extra bleed added.

Your fix works fine for me. All tiles I print at the print shop. For home printing though it will cost .002% more in ink. But for tiles it is just better for the color match and the cost of ink it print them at the shop.

Do you know?
Tyler McLaughlinpt.mclaughlin@shaw.ca<mailto:pt.mclaughlin@shaw.ca>

On Jul 9, 2019, at 6:06 PM, Galatolol <notifications@github.com<mailto:notifications@github.com>> wrote:


If I understand correctly<http://localhost:3000/images/CST25449_Hexes_Clear_Crop.jpg>, 37.5 is the distance to the border of an actual tile and not to those extra strips of colour.

Replacing
c.extraY = 25 + 37.5; // Half inch above the pins, rest below
with
c.extraY = 25 + 28; // Half inch above the pins, rest below
(in src/tilesheet/utils.js)
seems to fix it, but I feel that this is not the optimal solution.

**Comment by Galatolol** [comment]
I've opened a PR with a more elegant solution. #86
