### ISSUE TITLE
Allow for tile size and map tile size to be configured differently.

### ISSUE THREAD

**Issue by ckarlof** [kelsin/18xx#93]
It's helpful for game play if the map tile size is slightly larger than the track tiles, otherwise the border can get crowded, and it's more difficult manipulate the tiles. BGG thread for broader context: https://boardgamegeek.com/thread/1733893/tile-size-and-hex-size

Scott recommends 1.5" and 1.52", resp. Carthaginian's print-and-play art is 38mm and 40mm, resp.

**Comment by kelsin** [comment]
In the original code I did size up the map very slightly in order to do
this. I’m camping all weekend but when I’m i’ll Figure out where I used to
do this and bring it back configurable :)

**Comment by kelsin** [comment]
Yeah I removed this a stupid long time ago: https://github.com/kelsin/18xx/commit/b6506be13df98f56ce1e585e4f0cd6874c952953#diff-fca07c5f33f305889ce10f83871767b0

Would just having two hex size options be good enough? Right now I have good luck with printing with everything set with the defaults, are others finding the tiles too big?

**Comment by ckarlof** [comment]
Having two numbers to configure would be helpful. 1.5" tile hex size is fairly standard for non-GMT games, but the map hex size varies across games. I generally prefer the map hex size to be slightly larger than the tile hex size to make it easier to place and update tiles (i.e., having map hex size slightly larger leaves a little room to maneuver my fingers).

In terms of implementation, I don't have a strong opinion: explicit configuration of each size or a  size and a ratio for the other would both be fine.

**Comment by kelsin** [comment]
Added `mapWidth` as a new config option under `tiles` to set this and added to config page. Please let me know if you see issues with it. Remember that if you use the `die` or `smallDie` option for tiles that overrides the tile width to 150 and 106.25 (respectively).

**Comment by ckarlof** [comment]
👍
