### ISSUE TITLE
Allow for phase text color in offboardrevenue be controlled (or provide an example)

### ISSUE THREAD

**Issue by ngeunit1** [kelsin/18xx#95]
When creating an offboardrevenue atom (similar to 1870 offboards) it would be great if the phase number color could be controlled (and if it is, can you add an example for it in the atom examples?).

The use case here is that I have an offboard on the top row of a map that has track in it as well. And when I push the offboardrevenue up and a bit off the top of the hex, the white phase text blends with the white background. If this text could be controlled (set black for example) it would be fine hanging off the hex edge.

**Comment by kelsin** [comment]
Should be the `phaseColor` field. I'll add it to an atom like you said :)

**Comment by kelsin** [comment]
Added example!

**Comment by ngeunit1** [comment]
Awesome Thanks!
